name: imei_getter
description: A new Flutter project.
version: 0.0.4
homepage:

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.emir.imei_getter
        pluginClass: ImeiGetterPlugin
      ios:
        pluginClass: ImeiGetterPlugin